"""Render the benchmark report from the JSON records the other commands emit.

The headline question is efficiency: what fraction of the bare engine's throughput does
the Python pipeline hold? That is a ratio, so it needs a denominator measured on the same
GPU with the same token shape — `catalog-bench sol`.

The verdict is code rather than prose so it cannot drift under enthusiasm:

    >= 93% of bare-engine throughput   the pipeline is not the bottleneck; optimizing it
                                       buys nothing, and effort belongs on the engine,
                                       the prompt, or the schema
    <= 80%                             the pipeline IS the bottleneck; the per-stage host
                                       CPU breakdown says which stage to attack first
    in between                         inconclusive; widen the in-flight sweep

Three refusals are deliberate, because each prevents a number that looks like a
measurement and is not:

  * mock records never produce a verdict;
  * a verdict requires a real bare-engine baseline — without a denominator there is no
    ratio, and "the pipeline hit 4000 tok/s" is not evidence about anything;
  * the bare-engine baseline is a TensorRT-LLM in-process number, so it is only a valid
    denominator for in-process rows. Dividing a served-over-HTTP rate by it would compare
    two different engines and render the result as an efficiency.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

PIPELINE_NOT_BOTTLENECK = 0.93
PIPELINE_IS_BOTTLENECK = 0.80

# The bare-engine baseline is produced by trtllm-bench against the in-process engine, so
# only in-process rows share its denominator.
SOL_COMPARABLE_ENGINES = ("trtllm",)


def load_records(paths: list[Path]) -> list[dict[str, Any]]:
    records = []
    for p in paths:
        for f in ([p] if p.is_file() else sorted(p.glob("*.json"))):
            try:
                records.append(json.loads(f.read_text()))
            except json.JSONDecodeError:
                print(f"skipping unparseable {f}")
    return records


def _md_table(headers: list[str], rows: list[list[str]]) -> str:
    out = ["| " + " | ".join(headers) + " |",
           "|" + "|".join("---" for _ in headers) + "|"]
    out += ["| " + " | ".join(r) + " |" for r in rows]
    return "\n".join(out)


def _label(p: dict[str, Any]) -> str:
    """How a probe row identifies itself: engine and serving mode, never just 'Python'.

    Without this, a TensorRT-LLM row and a vLLM row at the same grammar and in-flight
    render as two identical-looking lines with different numbers.
    """
    serving = p.get("serving") or ("http" if p.get("engine") == "http" else "in-process")
    return f"{p.get('engine', '?')} ({serving})" + (" — MOCK" if p.get("mock") else "")


def build_report(records: list[dict[str, Any]]) -> str:
    tokens = [r for r in records if r.get("kind") == "tokens"]
    probes = [r for r in records if r.get("kind") == "probe"]
    baselines = [r for r in records if r.get("kind") == "sol_baseline"]

    any_mock = any(r.get("mock") for r in probes)
    sol = max((b["total_tokens_per_sec"] for b in baselines), default=None)
    real = [p for p in probes if not p.get("mock")]
    # In-process rows only: these are the ones the bare-engine denominator applies to.
    comparable = [p for p in real if p.get("engine") in SOL_COMPARABLE_ENGINES]
    # The like-for-like denominator for grammar-on rows is the pipeline's own unguided
    # run, within the same engine. trtllm-bench cannot isolate grammar cost because it is
    # always unguided.
    unguided = max((p["total_tokens_per_sec"] for p in comparable if p["grammar"] == "off"),
                   default=None)

    L = ["# Batch enrichment benchmark", "",
         "Generated by `catalog-bench report`.", ""]

    if any_mock:
        L += ["> ## MOCK DATA — NOT A MEASUREMENT",
              "> At least one record came from the mock engine, which simulates decode on",
              "> CPU. Those rows show the harness runs end to end. They say nothing about",
              "> throughput, and no verdict is rendered from them.", ""]

    if tokens:
        L += ["## 1. Tokens per product", "",
              "The denominator of every throughput and cost figure below. Measured on CPU",
              "with the real schema and the real prompt template, so it does not depend on",
              "the GPU run.", ""]
        L.append(_md_table(
            ["schema_mode", "tokenizer", "system prefix", "ISL mean", "ISL p95",
             "OSL (est)", "tok/product", "prefix share"],
            [[t["schema_mode"], t["tokenizer"], f"{t['system_prefix_tokens']}",
              f"{t['isl_mean']:.0f}", f"{t['isl_p95']}", f"{t['osl_estimate']}",
              f"**{t['tokens_per_product_mean']:.0f}**", f"{t['prefix_share']:.0%}"]
             for t in sorted(tokens, key=lambda x: x["tokens_per_product_mean"])]))
        L += ["", "Output length is estimated from the schema's bounds, not measured. The",
              "benchmark's `osl_mean` replaces it once a GPU run exists.", ""]

    L += ["## 2. Benchmark matrix", ""]
    if not probes and not baselines:
        L += ["_No benchmark or baseline records found._", ""]
    else:
        rows = []
        for b in baselines:
            rows.append(["bare engine (trtllm-bench)", "off", "—", f"{b['concurrency']}",
                         f"{b['total_tokens_per_sec']:,.0f}", f"{b['products_per_sec']:.1f}",
                         "—", "—", "—", "1.000 (defines the ceiling)"])
        for p in sorted(probes, key=lambda x: (x.get("engine", ""), x["grammar"],
                                               x["in_flight"])):
            if sol and p.get("engine") in SOL_COMPARABLE_ENGINES and not p.get("mock"):
                eff = f"{p['total_tokens_per_sec'] / sol:.3f}"
            else:
                eff = "—"
            rows.append([
                _label(p), p["grammar"], p["schema_mode"], f"{p['in_flight']}",
                f"{p['total_tokens_per_sec']:,.0f}", f"{p['products_per_sec']:.1f}",
                f"{p['goodput']:.3%}", f"{p['host_cpu_share_of_wall']:.0%}",
                f"{p['feeder_starvation_rate']:.1%}", eff,
            ])
        L.append(_md_table(
            ["config", "grammar", "schema", "in-flight", "tok/s", "products/s",
             "goodput", "host CPU", "feeder starved", "efficiency"], rows))
        L += ["",
              "`efficiency` is against the bare in-process engine and is left blank for",
              "served rows: a different engine's ceiling is not a meaningful denominator.",
              ""]

        # Valid products/sec is the metric that actually matters, and it is not the same
        # ranking as tok/s — unguided decoding produces tokens faster and a fifth of them
        # fail validation.
        if real:
            L += ["### Valid products/sec", "",
                  "Throughput times goodput. This is the deliverable rate, and it ranks",
                  "configurations differently from raw tok/s.", ""]
            L.append(_md_table(
                ["config", "grammar", "in-flight", "products/s", "goodput",
                 "valid products/s"],
                [[_label(p), p["grammar"], f"{p['in_flight']}",
                  f"{p['products_per_sec']:.2f}", f"{p['goodput']:.1%}",
                  f"**{p['products_per_sec'] * p['goodput']:.2f}**"]
                 for p in sorted(real, key=lambda x: -x["products_per_sec"] * x["goodput"])]))
            L.append("")

    if probes:
        L += ["## 3. Where host CPU is spent", "",
              "Share of *host CPU*, not wall clock. Time blocked in `drain` waiting on the",
              "GPU is the pipeline working correctly; charging it to the host would make a",
              "perfectly saturated pipeline look CPU-bound.", ""]
        stage_names = sorted({s for p in probes for s in p["stages"]["cpu_share_of_host"]})
        L.append(_md_table(
            ["config", "host CPU % of wall", *stage_names, "blocked on engine"],
            [[f"{_label(p)} {p['grammar']}/if{p['in_flight']}",
              f"{p['host_cpu_share_of_wall']:.0%}",
              *[f"{p['stages']['cpu_share_of_host'].get(s, 0):.0%}" for s in stage_names],
              f"{p['stages']['blocked_on_engine_share']:.0%}"]
             for p in probes]))
        L.append("")

    L += ["## 4. Questions this answers", ""]

    L.append("**Bare-engine ceiling.** " + (
        f"{sol:,.0f} total tok/s on the bare engine at this workload's token shape."
        if sol else "_Unanswered — needs a GPU. Run `catalog-bench sol`._"))

    L.append("")
    if unguided and any(p["grammar"] != "off" for p in comparable):
        on = max(p["total_tokens_per_sec"] for p in comparable if p["grammar"] != "off")
        L.append(f"**What guided decoding costs.** Grammar-on reaches {on:,.0f} tok/s "
                 f"against {unguided:,.0f} tok/s unguided through the same pipeline: "
                 f"**{1 - on / unguided:.1%}** of raw tokens. Weigh that against the "
                 "goodput column — the grammar usually returns more in valid output than "
                 "it costs in tokens. This is the like-for-like comparison; the "
                 "trtllm-bench baseline cannot isolate grammar cost because it is always "
                 "unguided.")
    else:
        L.append("**What guided decoding costs.** _Unanswered — needs non-mock runs with "
                 "`--grammar off` and `--grammar xgrammar` on the same engine and GPU._")

    L.append("")
    if tokens:
        best = min(tokens, key=lambda t: t["tokens_per_product_mean"])
        worst = max(tokens, key=lambda t: t["tokens_per_product_mean"])
        L.append(f"**Tokens per product.** {best['tokens_per_product_mean']:.0f} "
                 f"(`schema_mode={best['schema_mode']}`) to "
                 f"{worst['tokens_per_product_mean']:.0f} "
                 f"(`schema_mode={worst['schema_mode']}`), a "
                 f"**{worst['tokens_per_product_mean'] / best['tokens_per_product_mean']:.1f}x** "
                 "spread. Throughput moves inversely with this, so prompt construction is "
                 "worth as much as any engine tuning knob.")
    else:
        L.append("**Tokens per product.** _Unanswered — run `catalog-bench tokens`._")

    L.append("")
    if comparable and sol:
        best = max(comparable, key=lambda p: p["total_tokens_per_sec"])
        L.append(f"**Pipeline efficiency.** The best in-process configuration reaches "
                 f"{best['total_tokens_per_sec'] / sol:.1%} of the bare engine, burning "
                 f"{best['host_cpu_share_of_wall']:.0%} of a core with a feeder starvation "
                 f"rate of {best['feeder_starvation_rate']:.1%}.")
    else:
        L.append("**Pipeline efficiency.** _Unanswered — needs both an in-process GPU run "
                 "and a bare-engine baseline._")

    L += ["", "## 5. Verdict", "", verdict(probes, sol), ""]
    return "\n".join(L)


def verdict(probes: list[dict[str, Any]], sol: float | None) -> str:
    """The efficiency verdict. Reachable on its own, so it re-filters its own input."""
    comparable = [p for p in probes
                  if not p.get("mock") and p.get("engine") in SOL_COMPARABLE_ENGINES]
    if not comparable:
        served = sum(1 for p in probes
                     if not p.get("mock") and p.get("engine") not in SOL_COMPARABLE_ENGINES)
        extra = (f" {served} served record(s) were found and are not eligible: the bare-engine "
                 "baseline measures the in-process engine, so it is not their denominator."
                 if served else "")
        return ("**NO VERDICT.** No non-mock in-process records. The mock engine simulates "
                "decode on CPU; a verdict rendered from it would be an invented number." + extra)
    if sol is None:
        return ("**NO VERDICT.** No bare-engine baseline. Efficiency is a ratio and there is "
                "no denominator. Run `catalog-bench sol` on the same GPU and token shape.")

    best = max(comparable, key=lambda p: p["total_tokens_per_sec"])
    eff = best["total_tokens_per_sec"] / sol
    ctx = (f"Best in-process configuration: `grammar={best['grammar']}`, "
           f"`schema_mode={best['schema_mode']}`, in-flight {best['in_flight']} → "
           f"**{eff:.1%} of the bare engine**, host CPU "
           f"{best['host_cpu_share_of_wall']:.0%} of wall, feeder starved "
           f"{best['feeder_starvation_rate']:.1%} of polls.\n\n")

    if eff >= PIPELINE_NOT_BOTTLENECK:
        return ctx + (
            f"### The pipeline is not the bottleneck ({eff:.1%} ≥ "
            f"{PIPELINE_NOT_BOTTLENECK:.0%})\n\n"
            "A plain Python pipeline is holding the engine's throughput. Rewriting it in a "
            "faster language would buy nothing measurable here. Spend the effort on tokens "
            "per product (section 1), on the engine and concurrency level (section 2), or "
            "on goodput — all three move the deliverable rate more than the data plane can.")
    if eff <= PIPELINE_IS_BOTTLENECK:
        return ctx + (
            f"### The pipeline IS the bottleneck ({eff:.1%} ≤ {PIPELINE_IS_BOTTLENECK:.0%})\n\n"
            f"It is leaving {1 - eff:.0%} of the GPU idle, against a ceiling of "
            f"**{sol:,.0f} tok/s**. Use the section 3 host-CPU breakdown to pick the target: "
            "rebuild the stage that dominates it, re-measure, and only then look at the "
            "second one. Batched submit and cheaper validation are the usual first two wins.")
    return ctx + (
        f"### Inconclusive ({PIPELINE_IS_BOTTLENECK:.0%} < {eff:.1%} < "
        f"{PIPELINE_NOT_BOTTLENECK:.0%})\n\n"
        "Neither branch is supported, and this is not a question to settle by argument. "
        "Widen the in-flight sweep and confirm the feeder is not starving on something "
        "cheaply fixable. If it stays in this band, the honest reading is that a faster "
        "data plane buys a real but modest margin, and only for the stages section 3 "
        "actually implicates.")


def add_args(ap: argparse.ArgumentParser) -> None:
    ap.add_argument("inputs", nargs="*", type=Path, default=[Path("reports")],
                    help="record JSON files or directories (default: reports/)")
    ap.add_argument("--out", type=Path, default=Path("reports/benchmark_report.md"))


def main(args: argparse.Namespace) -> int:
    records = load_records(args.inputs or [Path("reports")])
    if not records:
        raise SystemExit("no records found — run the benchmark first")

    report = build_report(records)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(report)
    print(report)
    print(f"\nwrote {args.out}")
    return 0
